name = "PlotPlants"
uuid = "62700b34-1872-4917-b6af-4f42ae699f38"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "0.21"
DocStringExtensions = "0.8"
GLM = "1.3"
PyCall = "1.91"
PyPlot = "2.9"
julia = "1.3"
